# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
es:
  languageCode: es
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/es

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: 'Training Data Lab'
  params:
    description: 'Data Science in the Social Sciences and Humanities Research Group'
    footer:
        copyright:
            notice: '<i class="fa-brands fa-creative-commons"></i> 2020-{year} Training Data Lab has been supported and funded by'
  menu:
    main:
      - name: Team
        url: people
        weight: 10
      - name: News
        url: post
        weight: 20
      - name: Projects
        url: project
        weight: 30
      - name: Events
        url: event
        weight: 40
      - name: Publications
        url: publication
        weight: 50
      - name: Working Papers
        url: tufte-working-papers
        weight: 60
